# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
---
### Operating systems
# Fedora - http://fedoraproject.org
fedora_previous: 24
fedora_current: 25
fedora_next: 26

# phpMyAdmin- http://www.phpmyadmin.net
phpmyadmin_version: 4.6.6

